### PR TITLE
Throttling init

### PR DESCRIPTION
**Pull request by Aankirz**
## Steps:
</hr>
 
### In app:
Type chrome://throttle

### Demo Link:

<b>Dummy data</b>: (to check network throttling)
1.) set data to
>latency:200000
>download: 5000
>upload: 7000      (<i>This will lead to slower internet bandwidth</i>)

2. set data to
>latency:200
>download: 500000
>upload: 7000000    (<i>This will lead to relatively faster internet bandwidth</i>)

### APK Link:
https://drive.google.com/drive/folders/101D1ifg-H9d94RuYtui16sqIDjnsyqy5?usp=sharing

### CODE REVIEW

**Comment by sandys** [comment]
history of edits:
Steps to reproduce error:
In terminal
cd src

autoninja -C out/Default chrome_public_apk
In app:
Type chrome://throttling in the url

APK Link:
https://drive.google.com/file/d/1LovZFMSvdYNRwQ-DU5g0Z86TuYxVSg8-/view?usp=sharing

Code Locations:
src/chrome/browser/ui/webui/throttling

src/chrome/browser/resources/throttling

services/network/public/mojom/network_context.mojom
Error:
(Mojom related error), For Webui to execute we need PageHandler,PageHandlerFactory and Page interfaces in our mojom file. I imported the network_context.mojom, to expose the SetNetworkConditions in [chrome://throttling](https://github.com/wootzapp/wootz-browser/pull/URL).
image
image

**Comment by sandys** [comment]
history of error:
Steps to reproduce error:
In terminal
cd src

autoninja -C out/Default chrome_public_apk
In app:
Type chrome://throttle in the url

Type wootzapp://throttle in the URL, or try chrome://throttle

Issue description:
I am trying to expose the SetNetworkConditons (in the [network_context.mojom](https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/mojom/network_context.mojom;l=1253;drc=0586a538d8b452fe3da212737140878ed16eed49;bpv=0;bpt=1)) to the frontend so that user can give all the network conditions and set the throttling manually, similar to the network tab in chrome's devtools.

What I am trying to implement is similar to net_internals code, where they have also tried using network mojom. And my approach is quite similar to theirs.
[net_internals frontend](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/net_internals/)
[net_internals backend]
(https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/net_internals/net_internals_ui.h;bpv=0)

How devtools did it:
Browser side
[content/browser/devtools/protocol/network_handler.cc](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/network_handler.cc;l=1839;drc=0586a538d8b452fe3da212737140878ed16eed49;bpv=1;bpt=1)

Frontend side:
[third_party/devtools-frontend/src/front_end/core/sdk/NetworkManager.ts](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/sdk/NetworkManager.ts;l=1379?q=networkConditionsEqual&ss=chromium%2Fchromium%2Fsrc)

APK Link:
[https://drive.google.com/file/d/](https://drive.google.com/file/d/1hxhjkcuad2dpj3aOVQqL0wWS88oRSGdL/view?usp=sharing)[1LovZFMSvdYNRwQ-DU5g0Z86TuYxVSg8-/](https://drive.google.com/file/d/1LovZFMSvdYNRwQ-DU5g0Z86TuYxVSg8-/view?usp=sharing)[1hxhjkcuad2dpj3aOVQqL0wWS88oRSGdL/](https://drive.google.com/file/d/1hxhjkcuad2dpj3aOVQqL0wWS88oRSGdL/view?usp=sharing)[view?usp=sharing](https://drive.google.com/file/d/1hxhjkcuad2dpj3aOVQqL0wWS88oRSGdL/view?usp=sharing)

Code Locations:
For the browser code --> BACKEND CODE
src/chrome/browser/ui/webui/throttle       
src/chrome/browser/ui/webui/throttle

For the resources part --> FRONTEND CODE
src/chrome/browser/resources/throttle

Mojom part
services/network/public/mojom/network_context.mojom

image

**Comment by sandys** [comment]
history of error:

Steps to reproduce error:
In terminal
cd src

autoninja -C out/Default chrome_public_apk
In app:
Type wootzapp://throttle in the URL, or try chrome://throttle

Issue description:
I am trying to expose the SetNetworkConditons (in the [network_context.mojom](https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/mojom/network_context.mojom;l=1253;drc=0586a538d8b452fe3da212737140878ed16eed49;bpv=0;bpt=1)) to the frontend so that user can give all the network conditions and set the throttling manually, similar to the network tab in chrome's devtools.

What I am trying to implement is similar to net_internals code, where they have also tried using network mojom. And my approach is quite similar to theirs.
[net_internals frontend](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/net_internals/)
[net_internals backend]
(https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/net_internals/net_internals_ui.h;bpv=0)[net_internals backend](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/net_internals/net_internals_ui.h;bpv=0)

How devtools did it:
Browser side
[content/browser/devtools/protocol/network_handler.cc](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/network_handler.cc;l=1839;drc=0586a538d8b452fe3da212737140878ed16eed49;bpv=1;bpt=1)

Frontend side:
[third_party/devtools-frontend/src/front_end/core/sdk/NetworkManager.ts](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/sdk/NetworkManager.ts;l=1379?q=networkConditionsEqual&ss=chromium%2Fchromium%2Fsrc)

APK Link:
https://drive.google.com/file/d/1hxhjkcuad2dpj3aOVQqL0wWS88oRSGdL/view?usp=sharing

Code Locations:
For the browser code --> BACKEND CODE
src/chrome/browser/ui/webui/throttle       

For the resources part --> FRONTEND CODE
src/chrome/browser/resources/throttle

Mojom part
services/network/public/mojom/network_context.mojom
image

**Comment by sandys** [comment]
history of error:

Steps:
In app:
Type chrome://throttle

Demo Link:
Dummy data: (to check network throttling)
1.) set data to

latency:200000
download: 50000
upload: 70000 (This will lead to slower internet bandwidth)

latency:200000
download: 5000
upload: 7000 (This will lead to slower internet bandwidth)

set data to
latency:200000
download: 50000
upload: 700000 (This will lead to relatively faster internet bandwidth)

latency:200
download: 500000
upload: 7000000 (This will lead to relatively faster internet bandwidth)

APK Link:
https://drive.google.com/drive/folders/101D1ifg-H9d94RuYtui16sqIDjnsyqy5?usp=sharing

**Comment by sandys** [comment]
apologies to everyone for accidental overwrite of main comment.

**Comment by Aankirz** [comment]
Sincere apologies from my side, in a hurry edited the main content. sorry once again.

**Pull request merged**
