### PR TITLE
Enabling extensions in Wootz

### PR DESCRIPTION
**Pull request by ivs**
Wootz browser now building with `enable_extensions` flag. To make it happen all desktop UI related parts, desktop style tab management, WebApps(ability to make an app from webpage) and several other functionalities, unavailable on mobile were commented out.

PR is still in progress, several crashes still present, pls use as a reference, do not merge
Build arguments to reproduce locally below. `use_rtti` can cause troubles, feel free to omit(using it in debugging)

Main changes are in ```chrome/browser/BUILD.gn```, several files that were not available on android should be enabled there.
Also, turn off !android guards in several other build files.

Main changes 

Build arguments:
```
    target_os = "android"
    target_cpu = "x64"
    is_debug= true
    symbol_level = 2
    strip_debug_info = false
    use_rtti = true
    enable_hls_demuxer = false
    enable_nacl = false
    proprietary_codecs = true
    ffmpeg_branding = "Chrome"
    treat_warnings_as_errors=false
    enable_extensions=true
    is_java_debug = true
    incremental_install = true
    is_component_build = true
    android_static_analysis = "off"
    cc_wrapper="env CCACHE_SLOPPINESS=time_macros ccache"
```

### CODE REVIEW

**Comment by ivs** [comment]
#### Key Files and Changes

- **Browser Startup**:
  - **`src/chrome/browser/chrome_browser_main.cc`**  
    Modifications are made to initialize the extension systems as part of Chromium's startup process.
  - **Post-Browser Startup Initialization**:
    - **`void ChromeBrowserMainParts::PostBrowserStart()`**  
      Extensions-related services are initialized after the browser startup, including API hooks for extensions to interact with the Android environment. Here, a test extension is loaded from disk as part of the startup process.

- **Main Classes in Chromium Codebase**:
  - **Extension**: Represents a single Chrome extension and handles metadata such as permissions, version, etc.
  - **ExtensionService**: Manages the lifecycle of extensions, including loading, updating, and unloading extensions.
  - **ExtensionsRegistry**: A centralized registry that tracks all installed extensions, providing APIs to query extension data.

- **JNI Wrapper and Java Part**:
  - **Native C++ part: `src/chrome/browser/extensions/extensions_android.cc`**
  - **Java part: `src/chrome/android/java/src/org/chromium/chrome/browser/extensions/Extensions.java`**  
    This file provides the Java interface to interact with Chrome extensions on Android. It facilitates communication between the native extension system and the Java components on Android.
  - **Extensions Confirmation Dialog**:
    - **`src/chrome/android/java/src/org/chromium/chrome/browser/extensions/ExtensionsConfirmationDialog.java`**  
      This Java class handles UI dialogs for extension installation confirmation, using the Java interface to connect to native C++.

- **Extension Installation**:
  - **`src/chrome/browser/download/chrome_download_manager_delegate.cc`**  
    This file was updated to check if a downloaded file is a `.crx` (Chrome extension) file, and if so, to handle its installation directly within Android Chromium.

- **Wootz API**:
  - **Definitions: `src/chrome/common/extensions/api/wootz.json`**
  - **Implementation: `src/chrome/browser/extensions/api/wootz/wootz_api.h`**  
    For now, the **`chrome.wootz.info()`** function is implemented, which provides detailed information about the device.

#### Extending `chrome.wootz` API:
The `chrome.wootz` API was extended to provide access to specific browser internals. A corresponding `wootz.json` file defines the API, while the C++ implementation handles API requests from JavaScript. This allows extensions to interact with Android Chromium’s environment seamlessly.

**Comment by DevT75** [comment]
I have read the WootzApp CLA Document and I hereby sign the CLA

**Comment by DevT75** [comment]
recheck

**Comment by pandey019** [comment]
I have read the WootzApp CLA Document and I hereby sign the CLA

**Pull request merged**
